[[constraint]]
name = "github.com/aws/aws-sdk-go"
version = "1.13.8"

[[constraint]]
name = "github.com/go-chi/chi"
version = "3.3.2"

[[constraint]]
name = "github.com/go-kit/kit"
version = "0.6.0"

[[constraint]]
branch = "master"
name = "github.com/gocql/gocql"

[[constraint]]
branch = "master"
name = "github.com/kr/pretty"

[[constraint]]
branch = "master"
name = "github.com/minio/blake2b-simd"

[[constraint]]
name = "github.com/pkg/errors"
version = "0.8.0"

[[constraint]]
name = "github.com/satori/go.uuid"
version = "1.2.0"

[[constraint]]
name = "github.com/spf13/cobra"
version = "0.0.1"

[[constraint]]
name = "github.com/spf13/viper"
version = "1.0.0"

[prune]
go-tests = true
unused-packages = true