[[constraint]]
name    = "github.com/coreos/etcd"
version = "3.3.3"

[[constraint]]
name    = "github.com/go-kit/kit"
version = "0.7.0"

[[constraint]]
branch = "master"
name   = "github.com/kr/pretty"

[[constraint]]
name    = "github.com/pkg/errors"
version = "0.8.0"

[[constraint]]
name    = "github.com/satori/go.uuid"
version = "1.2.0"

[[constraint]]
name    = "github.com/spf13/cobra"
version = "0.0.2"

[[constraint]]
name    = "github.com/spf13/viper"
version = "1.0.2"

[prune]
go-tests        = true
unused-packages = true
