version: '3'
services:
  server:
    networks:
      main:
        aliases:
          - server
    environment:
      GOPATH: /opt/go
    build:
      context: ../..
      dockerfile: ./misc/example/flare/Dockerfile
    volumes:
      - ../..:/opt/go/src/github.com/diegobernardes/flare:ro
    ports:
      - 8080:8080

  producer:
    networks:
      main:
    environment:
      GOPATH: /opt/go
      TYPE: producer
    build:
      context: ../..
      dockerfile: ./misc/example/app/cmd/Dockerfile
    volumes:
      - ../..:/opt/go/src/github.com/diegobernardes/flare:ro

  consumer:
    networks:
      main:
        aliases:
          - consumer
    environment:
      GOPATH: "/opt/go"
      TYPE: consumer
    build:
      context: ../..
      dockerfile: ./misc/example/app/cmd/Dockerfile
    volumes:
      - ../..:/opt/go/src/github.com/diegobernardes/flare:ro

networks:
  main: