# --------------------------------------------------------------------------------------------------
# - http.server.addr
#   The address and port the HTTP server gonna listen. The value should have this format:
#   "address:port". The address can be omited, then, Flare gonna bind to all interfaces. The port is
#   required. Default value: ":8080"
#
# - http.default-limit
#   The quantity of entities to be returned by default. Default value: 30.
#
# - http.timeout
#   The max time a request has to process. Default value: 1s.
#
[http]
addr          = ":8080"
default-limit = 30
timeout       = "1s"

# --------------------------------------------------------------------------------------------------
# - repository.engine
#   The location of the content. Default value: "memory". Possible values: "memory" and "mongodb".
#
[repository]
engine = "memory"

# --------------------------------------------------------------------------------------------------
# - repository.addrs
#   List of "ip:port" to MongoDB servers. Default value: ["localhost:27017"]
#
# - repository.database
#   Name of the database on MongoDB. Default value: "flare"
#
# - repository.username
#   Username used to connect to MongoDB. Default value is unset.
#
# - repository.password
#   Password used to connect to MongoDB. Default value is unset.
#
[repository]
engine   = "mongodb"
addrs    = ["localhost:27017"]
database = "flare"
username = "flare"
password = "flare"

# --------------------------------------------------------------------------------------------------
# - task.engine
#   The engine used to enqueue jobs. If the 'sqs' is chosen, the 'aws' config block must be
#   configured. Possible values: "sqs" or "memory". Default value: "memory".
#
# - task.queue-document
#   If the SQS is used as engine, there is a option to set the queue name. Default value is
#   "flare-document-queue".
#
# - task.queue-subscription
#   If the SQS is used as engine, there is a option to set the queue name. Default value is
#   "flare-document-queue".
#
[task]
engine             = "sqs"
queue-document     = "flare-document-queue"
queue-subscription = "flare-subscription-queue"

# --------------------------------------------------------------------------------------------------
# - aws.key
#   Key used to connect to AWS. Default value is unset.
#
# - aws.secret
#   Secret used to connect to AWS. Default value is unset.
#
# - aws.region
#   Region used to connect to AWS. Default value is unset.
#
[aws]
key    = "key"
secret = "secret"
region = "us-east-1"

# --------------------------------------------------------------------------------------------------
# - log.level
#   The minimum log level to be displayed. Default value: "debug". Possible values: "debug", "info",
#   "warn" and "error".
#
# - log.output
#   Where the logs gonna be sent. Default value: "stdout". Possible values: "stdout" and "discard".
#
# - log.format
#   Format of the outputed log. Default value: "human". Possible values: "human" and "json".
#
[log]
level  = "debug"
output = "stdout"
format = "human"